### ISSUE TITLE
下载hand_tracking_aar.aar报错

### ISSUE THREAD

**Issue by mws100** [zhouzaihang/flutter_hand_tracking_plugin#12]
Error downloading object: android/libs/hand_tracking_aar.aar (e9e16b6): Smudge error: Error downloading android/libs/hand_tracking_aar.aar (e9e16b67719b7f6a53ec6295764d4c5a05f25b09ddfdefb165da2ebcfd60e9d2): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

您好，下载hand_tracking_aar.aar文件一直报错，可以把这个文件发到我的邮箱吗，谢谢。
946503298@qq.com

**Comment by zhouzaihang** [comment]
已发，请注意查收

**Comment by Deali-Axy** [comment]
同求一份这个文件，谢谢！

邮箱：admin@deali.cn

**Comment by zhouzaihang** [comment]
> 同求一份这个文件，谢谢！
> 
> 邮箱：[admin@deali.cn](mailto:admin@deali.cn)

链接: https://pan.baidu.com/s/1hLdrVmHhDOTVe9WG0jYXGw 提取码: 888r

**Comment by Deali-Axy** [comment]
> > 同求一份这个文件，谢谢！
> > 邮箱：[admin@deali.cn](mailto:admin@deali.cn)
> 
> 链接: https://pan.baidu.com/s/1hLdrVmHhDOTVe9WG0jYXGw 提取码: 888r

感谢！
