### ISSUE TITLE
Error fetching LFS data, over quota

### ISSUE THREAD

**Issue by pschuegr** [zhouzaihang/flutter_hand_tracking_plugin#13]
```
pschuegr@glitchy ~/dev/flutter_hand_tracking_plugin (master) $ git lfs fetch
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/zhouzaihang/flutter_hand_tracking_plugin.git/info/lfs'
```

Thanks!

**Comment by Hawkeye08** [comment]
Hey @zhouzaihang, I understand you are a student. An alternate approach could be uploading the AAR file to drive or https://androidfilehost.com/

Meanwhile, I need the AAR file, how can you share it?

**Comment by zhouzaihang** [comment]
> ```
> pschuegr@glitchy ~/dev/flutter_hand_tracking_plugin (master) $ git lfs fetch
> fetch: Fetching reference refs/heads/master
> batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
> error: failed to fetch some objects from 'https://github.com/zhouzaihang/flutter_hand_tracking_plugin.git/info/lfs'
> ```
> 
> Thanks!

链接: https://pan.baidu.com/s/1hLdrVmHhDOTVe9WG0jYXGw 提取码: 888r

**Comment by zhouzaihang** [comment]
> Hey @zhouzaihang, I understand you are a student. An alternate approach could be uploading the AAR file to drive or https://androidfilehost.com/
> 
> Meanwhile, I need the AAR file, how can you share it?

链接: https://pan.baidu.com/s/1hLdrVmHhDOTVe9WG0jYXGw 提取码: 888r
