### ISSUE TITLE
Cant seem to download from Baidu - LFS data over quota

### ISSUE THREAD

**Issue by Hawkeye08** [zhouzaihang/flutter_hand_tracking_plugin#14]
@zhouzaihang, Thanks for taking the time to upload the file to baidu. Unfortunately, I cant seem to download the file since I cant create an account. If its possible can you upload on Google Drive / Microsoft OneDrive / DropBox / any other direct file sharing website for a day? Ill upload it on AndroidFileHost for you, which would help anyone who cant access baidu in the future. Thanks :)

**Comment by zhouzaihang** [comment]
> @zhouzaihang, Thanks for taking the time to upload the file to baidu. Unfortunately, I cant seem to download the file since I cant create an account. If its possible can you upload on Google Drive / Microsoft OneDrive / DropBox / any other direct file sharing website for a day? Ill upload it on AndroidFileHost for you, which would help anyone who cant access baidu in the future. Thanks :)

https://stuzucceducn-my.sharepoint.com/:u:/g/personal/31701431_stu_zucc_edu_cn/EaN7gfMOittEpuLKP7SrZOsBMxVzhgEPXBil-P0EWozUQQ?e=AbtgNH

password: `zhzh.xyz`

**Comment by Hawkeye08** [comment]
Hi @zhouzaihang, I have uploaded the AAR file on MediaFire. Here is the link - https://www.mediafire.com/file/lnfc1km4stntpni/hand_tracking_aar.aar/file

You may want to edit the Readme for all your documents to point to this website, or your sharepoint, whatever you prefer! Thanks for your quick response :)

**Comment by zhouzaihang** [comment]
ok, thx

Arnav Agarwal <notifications@github.com> 于2021年3月6日周六 下午2:05写道：
