### ISSUE TITLE
hand_tracking_aar.aar无法download

### ISSUE THREAD

**Issue by Jowney23** [zhouzaihang/flutter_hand_tracking_plugin#16]
Error downloading object: android/libs/hand_tracking_aar.aar (e9e16b6): Smudge error: Error downloading android/libs/hand_tracking_aar.aar (e9e16b67719b7f6a53ec6295764d4c5a05f25b09ddfdefb165da2ebcfd60e9d2): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by zhouzaihang** [comment]
#14
