### ISSUE TITLE
Black Screen persists. Camera not working. We cannot see preview. Hand Tracking AAr file

### ISSUE THREAD

**Issue by MahdiParekh** [zhouzaihang/flutter_hand_tracking_plugin#17]
I built the hand tracking aar file along with binarypb according to the instruc.  given in your readme . (mediapipe latest ver and 0.7.5.) .
Surface texture is printing in the console showing frames are created.
But due to the black screen we cannot detect anything.

FLutter version used 2.2.1

![image](https://user-images.githubusercontent.com/40835602/122405285-8bf77e80-cf9d-11eb-9497-2722c7ae2c77.png)

![image](https://user-images.githubusercontent.com/40835602/122405395-a7fb2000-cf9d-11eb-9183-1447dd8b684c.png)
![image](https://user-images.githubusercontent.com/40835602/122405467-b47f7880-cf9d-11eb-9976-e3c2d5826046.png)
![image](https://user-images.githubusercontent.com/40835602/122405521-c19c6780-cf9d-11eb-9ce7-89342d084a78.png)
![image](https://user-images.githubusercontent.com/40835602/122405591-cd882980-cf9d-11eb-9cf8-f1b011618a29.png)

after putting the load() function in a BUILD file......

commands for new aar
bazel build -c opt --strip=ALWAYS   --host_crosstool_top=@bazel_tools//tools/cpp:toolchain  --fat_apk_cpu=arm64-v8a,armeabi-v7a 
    //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_hand_tracking.aar

command for binarypb
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu

#

**Comment by zhouzaihang** [comment]
#14
