### ISSUE TITLE
This repository is over its data quota.

### ISSUE THREAD

**Issue by PandaQQ** [zhouzaihang/flutter_hand_tracking_plugin#2]
Seem to clone this repo cannot succeed with below issue:
This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by zhouzaihang** [comment]
Yes, but I'm a student, I can't afford it. Maybe you coule give me a email address. I will send the project code by email.

**Comment by PandaQQ** [comment]
My email is u3534800@connect.hku.hk~ Thanks~

**Comment by zhouzaihang** [comment]
I have sent you a 100.97MB `hand_tracking_aar.aar` file by mail. Except for this .aar file, other code can be downloaded through `git clone`. You need to replace the .aar file under the path `flutter_hand_tracking_plugin/android/libs/hand_tracking_aar.aar`, and then compile and run the project. If the project still have problems, you can contact me through this issue or email(zhou@zhzh.xyz).

**Comment by PandaQQ** [comment]
Thanks~

**Comment by mstale007** [comment]
Hey, @zhouzaihang even I'm facing the same issue.
Will it be possible for you to send the `hand_tracking_aar.aar` by mail.
My email id:- mihir.tale18@vit.edu
Would really appreciate your help!
I really liked your work! Thanks in advance..!

**Comment by zhouzaihang** [comment]
ok

Mihir Tale <notifications@github.com> 于2020年6月21日周日 上午5:19写道：

**Comment by aashish2000** [comment]
Hi @zhouzaihang, I am also facing the same issue, can you please email the hand_tracking_aar.aar file by mail? 
Email ID: aash.ananth@gmail.com
Thank you

**Comment by AloxGit** [comment]
Hey, @zhouzaihang your work is amazing! 
Could you please mail me the file too?
Email ID: alok.anand.one@gmail.com
Thanks a lot!

**Comment by zhouzaihang** [comment]
> Hi @zhouzaihang, I am also facing the same issue, can you please email the hand_tracking_aar.aar file by mail?
> Email ID: [aash.ananth@gmail.com](mailto:aash.ananth@gmail.com)
> Thank you

🆗

**Comment by zhouzaihang** [comment]
> Hey, @zhouzaihang your work is amazing!
> Could you please mail me the file too?
> Email ID: [alok.anand.one@gmail.com](mailto:alok.anand.one@gmail.com)
> Thanks a lot!

🆗

**Comment by Zhiw** [comment]
Hi @zhouzaihang, I'm facing the same issue, and I build aar failed. Could you please mail me the aar file?
Email: karlkb81@gmail.com
I like your work
Thanks a lot!

**Comment by zhouzaihang** [comment]
> Hi @zhouzaihang, I'm facing the same issue, and I build aar failed. Could you please mail me the aar file?
> Email: [karlkb81@gmail.com](mailto:karlkb81@gmail.com)
> I like your work
> Thanks a lot!

OK.

**Comment by joshuaKnauber** [comment]
Hey, same issue here, could you send me the file to joshua.knauber@gmail.com?
Thanks for this project it's great!

**Comment by joshuaKnauber** [comment]
@zhouzaihang  Hey, same issue here, could you send me the file to joshua.knauber@gmail.com?
Thanks for this project it's great!

**Comment by zhouzaihang** [comment]
> @zhouzaihang Hey, same issue here, could you send me the file to [joshua.knauber@gmail.com](mailto:joshua.knauber@gmail.com)?
> Thanks for this project it's great!

OK

**Comment by zhouzaihang** [comment]
> @zhouzaihang Hey, same issue here, could you send me the file to [joshua.knauber@gmail.com](mailto:joshua.knauber@gmail.com)?
> Thanks for this project it's great!

OK

**Comment by levinvic** [comment]
I'm facing the same issue, please send me the file.
Email ID: levinvic123@gmail.com
Thank you!
