### ISSUE TITLE
Plugin deprecated

### ISSUE THREAD

**Issue by Maringmei** [zhouzaihang/flutter_hand_tracking_plugin#21]
Update to V2

**Comment by gummyWalrus** [comment]
Seems like the chinese government has stopped supporting this plugin,

Don't know, don't care, might give a shit later

**Comment by zhouzaihang** [comment]
This is just a personal project in my undergraduate period, which cannot be maintained due to busy personal work. Might update to V2 next holiday season, thanks.

**Comment by WsK** [comment]
> Seems like the chinese government has stopped supporting this plugin,
> 
> Don't know, don't care, might give a shit later

Someone shares a side project they did for free. You somehow feel entitled to make demands on people to do more free work for you?  How pathetic. No one is your slave.

**Comment by gummyWalrus** [comment]
> > Seems like the chinese government has stopped supporting this plugin,
> > 
> > Don't know, don't care, might give a shit later
> 
> Someone shares a side project they did for free. You somehow feel entitled to make demands on people to do more free work for you?  How pathetic. No one is your slave.  

Pls chill bro, I was just making a joke about the Readme being in Chinese, the project being unmaintained and the issues left open with no response. I sincerely apologize to @zhouzaihang my joke was not of good taste and I assure you that I am not considering anyone as a slave in the open source community. May aggressivity be overthrown.
