### ISSUE TITLE
app crashes on startup

### ISSUE THREAD

**Issue by ronelgazar** [zhouzaihang/flutter_hand_tracking_plugin#3]
Hi I have cloned your repository, and tried to run the example  but the app crashed in the emulator with no errors

I'm new to flutter so i hope you can help me 
Thanks in advance.

**Comment by ronelgazar** [comment]
by the way great documentation

**Comment by zhouzaihang** [comment]
I suggest you use a real device for debugging. The simulator will always have some problems, even if no errors are reported

**Comment by ronelgazar** [comment]
I just tried it on my real device it's the same result the app crashes.

**Comment by zhouzaihang** [comment]
Please confirm whether the size of the .aar file(`flutter_hand_tracking_plugin/android/libs/hand_tracking_aar.aar`) in your project exceeds 100MB, if only a few kb indicates that the .aar file you downloaded is incomplete

**Comment by ronelgazar** [comment]
The size of the hand_tracking_aar.aar file is 103.21600 MB

**Comment by zhouzaihang** [comment]
Please provide the log of the program running.

**Comment by ronelgazar** [comment]
![image](https://user-images.githubusercontent.com/31697794/83974178-0a820080-a8f4-11ea-9c9f-bd56f1762c30.png)

**Comment by zhouzaihang** [comment]
I think the problem may be in flutter sdk:

[https://github.com/flutter/flutter/issues/35989](https://github.com/flutter/flutter/issues/35989)

**Comment by ronelgazar** [comment]
thank you i will check, for now i will leave the issue open

**Comment by ronelgazar** [comment]
`[        ] E/AndroidRuntime(29352): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file
"/data/app/xyz.zhzh.flutter_hand_tracking_plugin_example-85Gsr80AchvFZfd26RsVNg==/base.apk"],nativeLibraryDirectories=[/data/app/xyz.zhzh.flutter_hand_tracking_plugin_example-85Gsr80AchvFZfd26RsVNg==/lib/x86_64, /data/app/xyz.zhzh.flutter_hand_tracking_plugin_example-85Gsr80AchvFZfd26RsVNg==/base.apk!/lib/x86_64,    
/system/lib64, /vendor/lib64]]] couldn't find "libmediapipe_jni.so"`

i found the issue. where is the  file libmediapipe_jni.so located ?

**Comment by sonsosad** [comment]
@ronelgazar How did you fix this problem?

**Comment by ronelgazar** [comment]
@sonsosad 
A bit late 😅, I don't remember how I did it but it something along these lines 
1. reinstalled the` hand_tracking.aar` file properly using android studio
2. Installed `mediapipe` on my pc in order find the `libmediapipe_jeni.so` and replaced the original one
3. updated my `flutter sdk` (It was before `null safety` was introduced so I am not sure if it is relevant anymore) 
4. built a debug apk
5. installed it on a physical device   
6. Done

Have a nice day and
I hope it is still relevant.

ronelgazar
