### ISSUE TITLE
Can't download aar file

### ISSUE THREAD

**Issue by cwallenwein** [zhouzaihang/flutter_hand_tracking_plugin#8]
When trying to clone the project, this happens:

`> git clone https://github.com/zhouzaihang/flutter_hand_tracking_plugin.git`
`Cloning into 'flutter_hand_tracking_plugin'...`
`remote: Enumerating objects: 162, done.`
`remote: Counting objects: 100% (162/162), done.`
`remote: Compressing objects: 100% (129/129), done.`
`remote: Total 405 (delta 65), reused 91 (delta 4), pack-reused 243`
`Receiving objects: 100% (405/405), 40.66 MiB | 3.72 MiB/s, done.`
`Resolving deltas: 100% (114/114), done.`
`Downloading android/libs/hand_tracking_aar.aar (106 MB)`
`Error downloading object: android/libs/hand_tracking_aar.aar (e9e16b6): Smudge error: Error downloading android/libs/hand_tracking_aar.aar (e9e16b67719b7f6a53ec6295764d4c5a05f25b09ddfdefb165da2ebcfd60e9d2): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
`

Is there a way to download the .aar file anyways?

Or can I create it myself? Did you simply use the steps as described in your blog post to create the .aar file?
https://zhzh.xyz/2020/03/01/Flutter/flutter-plugin-handtracking-landmark/#创建一个-mediapipe-aar
or could you share your BUILD file?

**Comment by zhouzaihang** [comment]
If you want to build aar files, you can refer to [this project](https://github.com/google/mediapipe/), which contains the BUILD files you need.
If you just need an aar file, I can send it to you by mail. #2

**Comment by cwallenwein** [comment]
Thank you very much :) I just sent you an email to zhou@zhzh.xyz

**Comment by HarenaGit** [comment]
Please #zhouzaihang , could I also get the .aar files by mail?
