### ISSUE TITLE
Expired date of the ".aar" file in git lfs

### ISSUE THREAD

**Issue by HarenaGit** [zhouzaihang/flutter_hand_tracking_plugin#9]
Please, how can I get the hand_tracking_aar.aar file?

**Comment by zhouzaihang** [comment]
Leave your email address, I will send it to you by email

**Comment by HarenaGit** [comment]
Thank you so much :) .. 
Down bellow is my Email address :

nyharena.access5@gmail.com

**Comment by zhouzaihang** [comment]
> Thank you so much :) ..
> Down bellow is my Email address :
> 
> [nyharena.access5@gmail.com](mailto:nyharena.access5@gmail.com)

OK
